export {default as Container} from './Container/Container';
export {default as Home} from './section/Header/page/home/Home';
export {default as Car} from './section/Header/page/Car/Car';
export {default as NotFound} from './section/Header/page/notFound/notFound';
export {default as Travel } from './section/Header/page/Travel/Travel';
export {default as Life } from './section/Header/page/life/life';
export {default as Contracts} from './section/Header/page/contracts/Contracts';
export {default as Health } from './section/Header/page/health/Health';
export {default as HomeIns } from './section/Header/page/homeIns/homeIns';
export {default as Paymethod } from './section/Header/paymethod/Paymethod';