export {default as Container} from './Container/Container';
export {default as Home} from './section/Header/bage/home/Home';
export {default as Car} from './section/Header/bage/Car/Car';
export {default as NotFound} from './section/Header/bage/notFound/notFound';
export {default as SignIn}from './section/Header/bage/sign_in/SignIn';
export {default as SignUP}from './section/Header/bage/sign_up/SignUp';
export {default as Bank } from './section/Header/bage/bank/Bank';
export {default as Life } from './section/Header/bage/life/life';
export {default as  Contracts} from './section/Header/bage/contracts/Contracts';
export {default as Health } from './section/Header/bage/health/Health';
